### PR TITLE
initial version of data CI

### PR DESCRIPTION
**Pull request by oscarbatori**
I cleaned out a bunch of cruft as this repo was somewhat experimental, whereas now it seems like it's going to contain actual code. I am happy to move it elsewhere if you like. The file to pay attention to is [this one](https://github.com/liquidata-inc/open-elections-tools/pull/1/files#diff-9d80a8699d1e7caf24e10b8ef95109c7), the rest is just clean up and organization.

Here is an example output: 
```
07-31 05:02:10 __main__     INFO     Showing exceptions for file /Users/oscarbatori/Documents/open-elections/openelections-data-pa/2018/counties/20181106__pa__general__delaware__precinct.csv
07-31 05:02:10 __main__     INFO     Column election_day missing from file
07-31 05:02:10 __main__     INFO     Column absentee missing from file
07-31 05:02:10 __main__     INFO     Column provisional missing from file
07-31 05:02:10 __main__     INFO     Column emergency missing from file
07-31 05:02:10 __main__     INFO     Column military missing from file
07-31 05:02:10 __main__     INFO     Column ivo missing from file
07-31 05:02:10 __main__     INFO     Column federal missing from file
07-31 05:02:10 __main__     INFO     Column winner missing from file
07-31 05:02:10 __main__     INFO     Column precinct_id missing from file
07-31 05:02:10 __main__     INFO     Column state_precinct_id missing from file
07-31 05:02:10 __main__     INFO     Column precinct_name missing from file
07-31 05:02:10 __main__     INFO     ValueTypeException caused by values for column votes not being of type <class 'int'>:
 {8636: '1,036', 8641: '1,044', 8646: '1,014', 8649: '1,023', 8653: '1,036', 8658: '1,044', 8663: '1,014', 8666: '1,023', 10460: '1,057', 10465: '1,086', 10478: '1,020', 10482: '1,057', 10487: '1,086', 10500: '1,020', 13336: '1,302', 13341: '1,301', 13346: '1,291', 13349: '1,278', 13352: '1,292', 13356: '1,302', 13361: '1,301', 13366: '1,291', 13369: '1,278', 13372: '1,292', 13376: '1,072', 13381: '1,073', 13386: '1,074', 13389: '1,051', 13392: '1,068', 13396: '1,072', 13401: '1,073', 13406: '1,074', 13409: '1,051', 13412: '1,068'}
```

The program essentially takes the file, parses it, checks for the presence of columns, and then verifies it can cast each value in a column to the target type for that column, and reports all salient information needed to fix. 

There invocation looks something like:
```
$ ~/open-elections-tools/open_elections/validation/data_issues_by_state.py --years 2018 --state pa --base-dir ~/open-elections/openelections-data-pa
```

To close this out I will wrap this up in a pytest that we can call from a GitHub Action for all repos for which we have a schema file defined.

Let me know if this meets your needs.

### CODE REVIEW

**Comment by oscarbatori** [comment]
This is a good point, and I have thought about it. In my attempt to make a coherent SQL database I first tried to capture all the tabulation buckets (i.e. `mail_in_votes`, `election_date_votes`, etc., that were not uniform across states). As you saw, I sort gave up on that and fell back to (`candidate`, `party`, `precinct`,..., `votes`).

The setup that would seem to make most sense to me would be:
- verify each file has the "primary key" of a the voting counts for a single candidate/office/year (implicitly state, party, etc.)
- validate the balance of the columns are "voting count" columns and are integer values (or can be transformed to integer value)

I think this would get us to basically "technical correctness", and would make it pretty easy to reify the whole thing as a database.

**Comment by dwillis** [comment]
Yeah, I think having a set of checks on the columns we must have (county, precinct, office, district, party, candidate and votes) and then a set of checks on other vote types (maybe even just listing any additional columns) would be useful enough and go a long way to fixing errors that would make a SQL interface difficult to use.

**Comment by oscarbatori** [comment]
Okay, so the schema for _every_ file should be:
```
office, string
district, integer
county, string
precinct, string
party, string
candidate, string
votes, integer
```

Then there are some number of extra integer columns based on whatever tabulation buckets the election administrator publishes. Each state has an file of "extra columns", like the one you created for PA, and if that's present we check those, otherwise we just check for this "core" schema.

Then all PRs to all repos are gated on passing that test.

Thoughts?

**Comment by dwillis** [comment]
@oscarbatori that works for me - we should restrict it to the openelections-data-{state} repos.

**Comment by oscarbatori** [comment]
Yes, that's what I have in mind. 

Sounds good. I should have have something final this weekend.

**Comment by oscarbatori** [comment]
@dwillis this now runs via `pytest` which is quite nice.

Question about distribution: should this set of tools be published as a PyPi package? Are there other utilities that you use that it would make sense to publish alongside these tools?

In general I am looking for the most coherent way to present a set of Python tools to the contributor base that makes them most likely to be useful.

I still need to add some unit tests and a command line interface, but we should figure out the packaging question.

**Comment by dwillis** [comment]
@oscarbatori I think it would be great to have it as a PyPi package, yes. Originally we tied various things to the core repository and I don't think that's a great strategy for people working on a single state.

**Comment by oscarbatori** [comment]
Great, I will setup the PyPi package, and once that's published and

Can I transfer technical ownership of this repo to you/Open Elections? I don't think Liquidata should "own" it. Obviously I will continue to maintain, but the PyPi package shouldn't link to a Liquidata repo.

You could also just create a repo `openelections-tools` or whatever, and I could push everything up to that.

Finally, can you make an admin of PA so I can fiddle with the test GitHub Action?

**Comment by dwillis** [comment]
@oscarbatori Sure - happy to have the repo transferred to us, and I've made you an admin on openelections-data-pa.

**Pull request merged**
